#!/bin/sh

# wait for resolv.conf so we can resolve ntp servers
i=0
while test ! -f /etc/resolv.conf -a $i -le 100; do
  sleep 0.2
  i=$(expr $i + 1)
done

# symlink persistent storage into /var/lib/chrony
mkdir -p /etc/sysconfig/chrony
ln -sf /etc/sysconfig/chrony /var/lib/chrony

# sync once before daemonizing so we can notify minisatip startup that 
# we have time
chronyd -f /etc/chronyd.conf -n -q
logger -p local0.notice "chronyd time synchronized to $(date), signaling minisatip startup"

# notify satip init script
echo "ok" | nc 127.0.0.1 998 2> /dev/null

# finally daemonize
chronyd -f /etc/chronyd.conf
