#!/bin/sh

test -r /etc/sysconfig/config && . /etc/sysconfig/config

if test "$OSCAMD" != "yes"; then
  exit 0
fi

mkdir -p /etc/sysconfig/oscam
if ! test -r /etc/sysconfig/oscam/oscam.conf; then
  cp /etc/oscam.* /etc/sysconfig/oscam
fi
exec oscamd -c /etc/sysconfig/oscam -u
